//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseControlSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int Account_Code { get; set; }
        public int CostCenterId_FK { get; set; }
        public int ExpenseId_FK { get; set; }
        public string Account_Name { get; set; }
        public System.DateTime Create_Date { get; set; }
        public string Created_by { get; set; }
        public System.DateTime Closed_date { get; set; }
        public string Closed_by { get; set; }
    
        public virtual Cost_Center Cost_Center { get; set; }
        public virtual Expense Expense { get; set; }
    }
}
