//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseControlSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MRC
    {
        public int MRC_Id { get; set; }
        public int ProductId_FK { get; set; }
        public string AccountId_FK { get; set; }
        public string Description { get; set; }
        public decimal Unit { get; set; }
        public int Pack_Size { get; set; }
        public decimal Unit_Rate { get; set; }
        public decimal Other_Charges { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
