//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseControlSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.MRCs = new HashSet<MRC>();
            this.Purchase_Transaction = new HashSet<Purchase_Transaction>();
        }
    
        public int ProductId { get; set; }
        public string Product_Name { get; set; }
        public string Terms_code { get; set; }
        public int Item_CategoryId_FK { get; set; }
        public int Product_Type { get; set; }
        public int Pack_Size { get; set; }
    
        public virtual Item_Category Item_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MRC> MRCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase_Transaction> Purchase_Transaction { get; set; }
    }
}
