
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PurchaseControlSystem.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Purchase_Header
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Purchase_Header()
    {

        this.Verified_Transaction = new HashSet<Verified_Transaction>();

        this.Purchase_Transaction = new HashSet<Purchase_Transaction>();

    }


    public int OrderNo { get; set; }

    public int CostCenterId_FK { get; set; }

    public string AccountId_FK { get; set; }

    public string LpoStatus { get; set; }

    public string CreatedBy { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public string AmendedBy { get; set; }

    public Nullable<System.DateTime> AmendedDate { get; set; }

    public string Notes { get; set; }

    public string FinanceApproved { get; set; }

    public string OperationApproved { get; set; }

    public string InitalsBy { get; set; }

    public string Comments { get; set; }

    public int DepartmentId_FK { get; set; }



    public virtual Cost_Center Cost_Center { get; set; }

    public virtual Supplier Supplier { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Verified_Transaction> Verified_Transaction { get; set; }

    public virtual Department Department { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Purchase_Transaction> Purchase_Transaction { get; set; }

}

}
