
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PurchaseControlSystem.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Purchase_Transaction
{

    public int Purchase_TransactionId { get; set; }

    public int OrderNo_FK { get; set; }

    public int CostCenterId_FK { get; set; }

    public int ProductId_FK { get; set; }

    public string ProductName { get; set; }

    public Nullable<decimal> UnitPrice { get; set; }

    public Nullable<decimal> Quantity { get; set; }

    public Nullable<int> PackSize { get; set; }

    public Nullable<decimal> GrossValue { get; set; }

    public Nullable<System.DateTime> ReceiveDate { get; set; }

    public string ReceiveBy { get; set; }

    public string VarifiedBy { get; set; }

    public Nullable<System.DateTime> VarifiedDate { get; set; }

    public int ItemCategoryId_FK { get; set; }

    public int TermsCode { get; set; }

    public string AccountId_FK { get; set; }

    public string TermsPrinted { get; set; }

    public int Suffix_FK { get; set; }

    public string LpoStatus { get; set; }

    public string FinanceApproved { get; set; }

    public string OperationApproved { get; set; }

    public Nullable<decimal> CurrentValue { get; set; }

    public Nullable<decimal> BaseValue { get; set; }

    public Nullable<decimal> CurrentVAT { get; set; }

    public Nullable<decimal> BaseVAT { get; set; }



    public virtual Cost_Center Cost_Center { get; set; }

    public virtual Item_Category Item_Category { get; set; }

    public virtual Product Product { get; set; }

    public virtual Purchase_Header Purchase_Header { get; set; }

    public virtual Supplier Supplier { get; set; }

    public virtual Suffix Suffix { get; set; }

}

}
