//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseControlSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_Transaction
    {
        public int Purchase_TransactionId { get; set; }
        public int OrderNo_FK { get; set; }
        public int CostCenterId_FK { get; set; }
        public int ProductId_FK { get; set; }
        public string Status { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal Quantity { get; set; }
        public decimal GrossValue { get; set; }
        public System.DateTime Receive_date { get; set; }
        public string receive_by { get; set; }
        public string Varified_by { get; set; }
        public System.DateTime Varified_date { get; set; }
        public int Item_CategoryId_FK { get; set; }
        public int Terms_code { get; set; }
        public int Verified_TransactionId_FK { get; set; }
        public string AccountId_FK { get; set; }
        public string Terms_Printed { get; set; }
        public string Suffix { get; set; }
    
        public virtual Cost_Center Cost_Center { get; set; }
        public virtual Item_Category Item_Category { get; set; }
        public virtual Product Product { get; set; }
        public virtual Purchase_Header Purchase_Header { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Verified_Transaction Verified_Transaction { get; set; }
    }
}
