//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseControlSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suffix
    {
        public int Suffix_Id { get; set; }
        public string Suffix1 { get; set; }
        public int Expense { get; set; }
        public int DivisionId_FK { get; set; }
        public string Name { get; set; }
    
        public virtual Division Division { get; set; }
    }
}
