
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PurchaseControlSystem.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Supplier
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Supplier()
    {

        this.MRCs = new HashSet<MRC>();

        this.Supplier_SLA = new HashSet<Supplier_SLA>();

        this.Purchase_Header = new HashSet<Purchase_Header>();

        this.Verified_Transaction = new HashSet<Verified_Transaction>();

        this.Purchase_Transaction = new HashSet<Purchase_Transaction>();

    }


    public string AccountId { get; set; }

    public string Short { get; set; }

    public string Name { get; set; }

    public string Address1 { get; set; }

    public string Address2 { get; set; }

    public string Address3 { get; set; }

    public string Address4 { get; set; }

    public string Address5 { get; set; }

    public string Phone { get; set; }

    public string Currency_FK { get; set; }

    public int DivisionId_FK { get; set; }

    public int CreditTerms { get; set; }

    public string VAT_Group_FK { get; set; }

    public string VAT_Code_FK { get; set; }

    public string Acccount_Type { get; set; }

    public int NLCONTROL { get; set; }

    public string Supplier_Category { get; set; }

    public string Email { get; set; }



    public virtual Division Division { get; set; }

    public virtual Exchange_Rate Exchange_Rate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MRC> MRCs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Supplier_SLA> Supplier_SLA { get; set; }

    public virtual VAT_Code VAT_Code { get; set; }

    public virtual VAT_Group VAT_Group { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Purchase_Header> Purchase_Header { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Verified_Transaction> Verified_Transaction { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Purchase_Transaction> Purchase_Transaction { get; set; }

}

}
