//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseControlSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_Quotes
    {
        public string OrderNo { get; set; }
        public string Account1 { get; set; }
        public string File1 { get; set; }
        public string Account2 { get; set; }
        public string File2 { get; set; }
        public string Acccount3 { get; set; }
        public string File3 { get; set; }
        public string Account4 { get; set; }
        public string File4 { get; set; }
        public string Account5 { get; set; }
        public string File5 { get; set; }
    }
}
