
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PurchaseControlSystem.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Supplier_SLA
{

    public int Supplier_SLAId { get; set; }

    public string AccountId_FK { get; set; }

    public string SLA_Image { get; set; }



    public virtual Supplier Supplier { get; set; }

}

}
