//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseControlSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Authorise
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_Authorise()
        {
            this.Users = new HashSet<User>();
        }
    
        public string Username { get; set; }
        public string User_Authorisor1 { get; set; }
        public Nullable<decimal> Auth1_Llimit { get; set; }
        public Nullable<decimal> Auth1_Ulimit { get; set; }
        public string User_Authorisor2 { get; set; }
        public Nullable<decimal> Auth2_Llimit { get; set; }
        public Nullable<decimal> Auth2_Ulimit { get; set; }
        public string User_Authorisor3 { get; set; }
        public Nullable<decimal> Auth3_Llimit { get; set; }
        public Nullable<decimal> Auth3_Ulimit { get; set; }
        public string User_Authorisor4 { get; set; }
        public Nullable<decimal> Auth4_Llimit { get; set; }
        public Nullable<decimal> Auth4_Ulimit { get; set; }
        public string User_Authorisor5 { get; set; }
        public Nullable<decimal> Auth5_Llimit { get; set; }
        public Nullable<decimal> Auth5_Ulimit { get; set; }
        public string User_Authorisor6 { get; set; }
        public Nullable<decimal> Auth6_Llimit { get; set; }
        public Nullable<decimal> Auth6_Ulimit { get; set; }
        public string User_Authorisor7 { get; set; }
        public Nullable<decimal> Auth7_Llimit { get; set; }
        public Nullable<decimal> Auth7_Ulimit { get; set; }
        public string User_Authorisor8 { get; set; }
        public Nullable<decimal> Auth8_Llimit { get; set; }
        public Nullable<decimal> Auth8_Ulimit { get; set; }
        public string User_Authorisor9 { get; set; }
        public Nullable<decimal> Auth9_Llimit { get; set; }
        public Nullable<decimal> Auth9_Ulimit { get; set; }
        public string User_Authorisor10 { get; set; }
        public Nullable<decimal> Auth10_Llimit { get; set; }
        public Nullable<decimal> Auth10_Ulimit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
