
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PurchaseControlSystem.Models
{

using System;
    using System.Collections.Generic;
    
public partial class User
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public User()
    {

        this.User_Authorise = new HashSet<User_Authorise>();

    }


    public int UserId { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public int EmployeeNo { get; set; }

    public string Name { get; set; }

    public int DepartmentId_FK { get; set; }

    public int CostCenter_FK { get; set; }

    public string Email { get; set; }

    public int Phone { get; set; }

    public int Role { get; set; }

    public string PrintFormat { get; set; }

    public int DivisionAccess { get; set; }

    public int Grade { get; set; }

    public bool OperationsApprover { get; set; }

    public bool FinanceApprover { get; set; }

    public bool VendModAccess { get; set; }

    public string Signature { get; set; }

    public string TeamApplicable { get; set; }

    public int TeamId_FK { get; set; }

    public string Out_Of_Office { get; set; }

    public System.DateTime StartDate { get; set; }

    public System.DateTime EndDate { get; set; }

    public System.DateTime Comments { get; set; }

    public string Location_FK { get; set; }

    public int Terminal { get; set; }



    public virtual Cost_Center Cost_Center { get; set; }

    public virtual Department Department { get; set; }

    public virtual Location Location { get; set; }

    public virtual Team Team { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<User_Authorise> User_Authorise { get; set; }

}

}
