//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseControlSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Verified_Transaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Verified_Transaction()
        {
            this.Purchase_Transaction = new HashSet<Purchase_Transaction>();
        }
    
        public int Verified_TransactionId { get; set; }
        public int OrderNo_FK { get; set; }
        public int CostCenter_FK { get; set; }
        public string Supplier_Ref { get; set; }
        public string Misc_ref { get; set; }
        public System.DateTime Document_Date { get; set; }
        public System.DateTime Due_Date { get; set; }
        public int AccountCode { get; set; }
        public string Suffix { get; set; }
        public string VATCode { get; set; }
        public decimal Amount { get; set; }
        public string Narrative { get; set; }
        public string AccountId_FK { get; set; }
        public string Ptran_Ref { get; set; }
        public System.DateTime PostingDate { get; set; }
        public string Varified_by { get; set; }
        public System.DateTime Varified_date { get; set; }
        public string Export_Flg { get; set; }
    
        public virtual Cost_Center Cost_Center { get; set; }
        public virtual Purchase_Header Purchase_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase_Transaction> Purchase_Transaction { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
