
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PurchaseControlSystem.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Verified_Transaction
{

    public int Verified_TransactionId { get; set; }

    public int OrderNo_FK { get; set; }

    public int CostCenter_FK { get; set; }

    public string Supplier_Ref { get; set; }

    public string MiscRef { get; set; }

    public System.DateTime Document_Date { get; set; }

    public System.DateTime DueDate { get; set; }

    public int AccountCode { get; set; }

    public string Suffix { get; set; }

    public string VATCode { get; set; }

    public decimal Amount { get; set; }

    public string Narrative { get; set; }

    public string AccountId_FK { get; set; }

    public string PurchaseTransactionRef { get; set; }

    public System.DateTime PostingDate { get; set; }

    public string VarifiedBy { get; set; }

    public System.DateTime VarifiedDate { get; set; }

    public string ExportFlag { get; set; }



    public virtual Cost_Center Cost_Center { get; set; }

    public virtual Purchase_Header Purchase_Header { get; set; }

    public virtual Supplier Supplier { get; set; }

}

}
